-- MySQL Script generated by MySQL Workbench
-- Sat Jun 20 22:28:03 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Proyecto_de_investigacion
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Proyecto_de_investigacion
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Proyecto_de_investigacion` DEFAULT CHARACTER SET utf8 ;
USE `Proyecto_de_investigacion` ;

-- -----------------------------------------------------
-- Table `Proyecto_de_investigacion`.`Proyecto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Proyecto_de_investigacion`.`Proyecto` (
  `Proy_ID` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `Descripcion` TEXT NOT NULL,
  `Estado` VARCHAR(225) NOT NULL DEFAULT 'En preparativos',
  PRIMARY KEY (`Proy_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Proyecto_de_investigacion`.`Reunion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Proyecto_de_investigacion`.`Reunion` (
  `Reunion_ID` INT NOT NULL AUTO_INCREMENT,
  `Titulo` VARCHAR(225) NOT NULL,
  `Descripcion` TEXT NULL,
  `Lugar` VARCHAR(225) NOT NULL,
  `Fecha` DATETIME NOT NULL,
  `Proyecto_Proy_ID` INT NOT NULL,
  PRIMARY KEY (`Reunion_ID`, `Proyecto_Proy_ID`),
  INDEX `fk_Reunion_Proyecto1_idx` (`Proyecto_Proy_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Reunion_Proyecto1`
    FOREIGN KEY (`Proyecto_Proy_ID`)
    REFERENCES `Proyecto_de_investigacion`.`Proyecto` (`Proy_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Proyecto_de_investigacion`.`Entregables`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Proyecto_de_investigacion`.`Entregables` (
  `Ent_ID` INT NOT NULL AUTO_INCREMENT,
  `Titulo` VARCHAR(225) NOT NULL,
  `Descripcion` TEXT NULL,
  `Fecha` DATETIME NOT NULL,
  `Proyecto_Proy_ID` INT NOT NULL,
  PRIMARY KEY (`Ent_ID`, `Proyecto_Proy_ID`),
  INDEX `fk_Entregables_Proyecto1_idx` (`Proyecto_Proy_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Entregables_Proyecto1`
    FOREIGN KEY (`Proyecto_Proy_ID`)
    REFERENCES `Proyecto_de_investigacion`.`Proyecto` (`Proy_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Proyecto_de_investigacion`.`Reporte`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Proyecto_de_investigacion`.`Reporte` (
  `Rep_ID` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(225) NOT NULL,
  `Fecha_inicial` DATETIME NOT NULL,
  `Fecha_final` DATETIME NOT NULL,
  `Proyecto_Proy_ID` INT NOT NULL,
  PRIMARY KEY (`Rep_ID`, `Proyecto_Proy_ID`),
  INDEX `fk_Reporte_Proyecto1_idx` (`Proyecto_Proy_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Reporte_Proyecto1`
    FOREIGN KEY (`Proyecto_Proy_ID`)
    REFERENCES `Proyecto_de_investigacion`.`Proyecto` (`Proy_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Proyecto_de_investigacion`.`Viaje`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Proyecto_de_investigacion`.`Viaje` (
  `Viaje_ID` INT NOT NULL AUTO_INCREMENT,
  `Fecha_inicial` DATETIME NOT NULL,
  `Fecha_final` DATETIME NOT NULL,
  `Motivo` VARCHAR(225) NULL,
  `Lugar` VARCHAR(225) NOT NULL,
  `Proyecto_Proy_ID` INT NOT NULL,
  PRIMARY KEY (`Viaje_ID`, `Proyecto_Proy_ID`),
  INDEX `fk_Viaje_Proyecto1_idx` (`Proyecto_Proy_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Viaje_Proyecto1`
    FOREIGN KEY (`Proyecto_Proy_ID`)
    REFERENCES `Proyecto_de_investigacion`.`Proyecto` (`Proy_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Proyecto_de_investigacion`.`Presentacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Proyecto_de_investigacion`.`Presentacion` (
  `Presentacion_ID` INT NOT NULL AUTO_INCREMENT,
  `Titulo` VARCHAR(225) NOT NULL,
  `Fecha` DATETIME NOT NULL,
  `Lugar` VARCHAR(225) NOT NULL,
  `Presentador` VARCHAR(225) NOT NULL,
  `Descripcion` TEXT NULL,
  `Proyecto_Proy_ID` INT NOT NULL,
  PRIMARY KEY (`Presentacion_ID`, `Proyecto_Proy_ID`),
  INDEX `fk_Presentacion_Proyecto1_idx` (`Proyecto_Proy_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Presentacion_Proyecto1`
    FOREIGN KEY (`Proyecto_Proy_ID`)
    REFERENCES `Proyecto_de_investigacion`.`Proyecto` (`Proy_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Proyecto_de_investigacion`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Proyecto_de_investigacion`.`users` (
  `User_ID` INT NOT NULL AUTO_INCREMENT,
  `Email` VARCHAR(225) NOT NULL,
  `Password` VARCHAR(32) NOT NULL,
  `Usuario` VARCHAR(225) NOT NULL,
  `Descripción` TEXT NULL,
  PRIMARY KEY (`User_ID`));


-- -----------------------------------------------------
-- Table `Proyecto_de_investigacion`.`Inv_proy`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Proyecto_de_investigacion`.`Inv_proy` (
  `INV_ID` INT NOT NULL AUTO_INCREMENT,
  `Fecha` DATETIME NOT NULL,
  `Estado` VARCHAR(225) NOT NULL DEFAULT 'En espera',
  `Proyecto_Proy_ID` INT NOT NULL,
  `users_User_ID` INT NOT NULL,
  PRIMARY KEY (`INV_ID`, `Proyecto_Proy_ID`, `users_User_ID`),
  INDEX `fk_Notificacion_Proyecto1_idx` (`Proyecto_Proy_ID` ASC) VISIBLE,
  INDEX `fk_Notificacion_users1_idx` (`users_User_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Notificacion_Proyecto1`
    FOREIGN KEY (`Proyecto_Proy_ID`)
    REFERENCES `Proyecto_de_investigacion`.`Proyecto` (`Proy_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Notificacion_users1`
    FOREIGN KEY (`users_User_ID`)
    REFERENCES `Proyecto_de_investigacion`.`users` (`User_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Proyecto_de_investigacion`.`Documento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Proyecto_de_investigacion`.`Documento` (
  `Doc_ID` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `Descripcion` TEXT NULL,
  `Proyecto_Proy_ID` INT NOT NULL,
  `URL` VARCHAR(225) NOT NULL,
  PRIMARY KEY (`Doc_ID`, `Proyecto_Proy_ID`),
  INDEX `fk_Documento_Proyecto1_idx` (`Proyecto_Proy_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Documento_Proyecto1`
    FOREIGN KEY (`Proyecto_Proy_ID`)
    REFERENCES `Proyecto_de_investigacion`.`Proyecto` (`Proy_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Proyecto_de_investigacion`.`Categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Proyecto_de_investigacion`.`Categoria` (
  `Categoria_ID` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(225) NOT NULL,
  PRIMARY KEY (`Categoria_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Proyecto_de_investigacion`.`users_has_Proyecto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Proyecto_de_investigacion`.`users_has_Proyecto` (
  `users_User_ID` INT NOT NULL,
  `Proyecto_Proy_ID` INT NOT NULL,
  `JP` BINARY(1) NOT NULL DEFAULT 0,
  `Permiso` BINARY(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`users_User_ID`, `Proyecto_Proy_ID`),
  INDEX `fk_users_has_Proyecto_Proyecto1_idx` (`Proyecto_Proy_ID` ASC) VISIBLE,
  INDEX `fk_users_has_Proyecto_users1_idx` (`users_User_ID` ASC) VISIBLE,
  CONSTRAINT `fk_users_has_Proyecto_users1`
    FOREIGN KEY (`users_User_ID`)
    REFERENCES `Proyecto_de_investigacion`.`users` (`User_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_has_Proyecto_Proyecto1`
    FOREIGN KEY (`Proyecto_Proy_ID`)
    REFERENCES `Proyecto_de_investigacion`.`Proyecto` (`Proy_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `Proyecto_de_investigacion`.`Categoria_has_Proyecto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Proyecto_de_investigacion`.`Categoria_has_Proyecto` (
  `Categoria_Cat_ID` INT NOT NULL,
  `Proyecto_Proy_ID` INT NOT NULL,
  PRIMARY KEY (`Categoria_Cat_ID`, `Proyecto_Proy_ID`),
  INDEX `fk_Categoria_has_Proyecto_Proyecto1_idx` (`Proyecto_Proy_ID` ASC) VISIBLE,
  INDEX `fk_Categoria_has_Proyecto_Categoria1_idx` (`Categoria_Cat_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Categoria_has_Proyecto_Categoria1`
    FOREIGN KEY (`Categoria_Cat_ID`)
    REFERENCES `Proyecto_de_investigacion`.`Categoria` (`Categoria_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Categoria_has_Proyecto_Proyecto1`
    FOREIGN KEY (`Proyecto_Proy_ID`)
    REFERENCES `Proyecto_de_investigacion`.`Proyecto` (`Proy_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Proyecto_de_investigacion`.`Presentacion_has_users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Proyecto_de_investigacion`.`Presentacion_has_users` (
  `Presentacion_Presentacion_ID` INT NOT NULL,
  `Presentacion_Proyecto_Proy_ID` INT NOT NULL,
  `users_User_ID` INT NOT NULL,
  PRIMARY KEY (`Presentacion_Presentacion_ID`, `Presentacion_Proyecto_Proy_ID`, `users_User_ID`),
  INDEX `fk_Presentacion_has_users_users1_idx` (`users_User_ID` ASC) VISIBLE,
  INDEX `fk_Presentacion_has_users_Presentacion1_idx` (`Presentacion_Presentacion_ID` ASC, `Presentacion_Proyecto_Proy_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Presentacion_has_users_Presentacion1`
    FOREIGN KEY (`Presentacion_Presentacion_ID` , `Presentacion_Proyecto_Proy_ID`)
    REFERENCES `Proyecto_de_investigacion`.`Presentacion` (`Presentacion_ID` , `Proyecto_Proy_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Presentacion_has_users_users1`
    FOREIGN KEY (`users_User_ID`)
    REFERENCES `Proyecto_de_investigacion`.`users` (`User_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Proyecto_de_investigacion`.`Reunion_has_users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Proyecto_de_investigacion`.`Reunion_has_users` (
  `Reunion_Reunion_ID` INT NOT NULL,
  `Reunion_Proyecto_Proy_ID` INT NOT NULL,
  `users_User_ID` INT NOT NULL,
  PRIMARY KEY (`Reunion_Reunion_ID`, `Reunion_Proyecto_Proy_ID`, `users_User_ID`),
  INDEX `fk_Reunion_has_users_users1_idx` (`users_User_ID` ASC) VISIBLE,
  INDEX `fk_Reunion_has_users_Reunion1_idx` (`Reunion_Reunion_ID` ASC, `Reunion_Proyecto_Proy_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Reunion_has_users_Reunion1`
    FOREIGN KEY (`Reunion_Reunion_ID` , `Reunion_Proyecto_Proy_ID`)
    REFERENCES `Proyecto_de_investigacion`.`Reunion` (`Reunion_ID` , `Proyecto_Proy_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Reunion_has_users_users1`
    FOREIGN KEY (`users_User_ID`)
    REFERENCES `Proyecto_de_investigacion`.`users` (`User_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Proyecto_de_investigacion`.`Documento_has_Entregables`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Proyecto_de_investigacion`.`Documento_has_Entregables` (
  `Documento_Doc_ID` INT NOT NULL,
  `Documento_Proyecto_Proy_ID` INT NOT NULL,
  `Entregables_Ent_ID` INT NOT NULL,
  `Entregables_Proyecto_Proy_ID` INT NOT NULL,
  PRIMARY KEY (`Documento_Doc_ID`, `Documento_Proyecto_Proy_ID`, `Entregables_Ent_ID`, `Entregables_Proyecto_Proy_ID`),
  INDEX `fk_Documento_has_Entregables_Entregables1_idx` (`Entregables_Ent_ID` ASC, `Entregables_Proyecto_Proy_ID` ASC) VISIBLE,
  INDEX `fk_Documento_has_Entregables_Documento1_idx` (`Documento_Doc_ID` ASC, `Documento_Proyecto_Proy_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Documento_has_Entregables_Documento1`
    FOREIGN KEY (`Documento_Doc_ID` , `Documento_Proyecto_Proy_ID`)
    REFERENCES `Proyecto_de_investigacion`.`Documento` (`Doc_ID` , `Proyecto_Proy_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Documento_has_Entregables_Entregables1`
    FOREIGN KEY (`Entregables_Ent_ID` , `Entregables_Proyecto_Proy_ID`)
    REFERENCES `Proyecto_de_investigacion`.`Entregables` (`Ent_ID` , `Proyecto_Proy_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Proyecto_de_investigacion`.`Viaje_documentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Proyecto_de_investigacion`.`Viaje_documentos` (
  `Documento_ID` INT NOT NULL AUTO_INCREMENT,
  `URL` VARCHAR(255) NOT NULL,
  `Viaje_Viaje_ID` INT NOT NULL,
  `Viaje_Proyecto_Proy_ID` INT NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Documento_ID`, `Viaje_Viaje_ID`, `Viaje_Proyecto_Proy_ID`),
  INDEX `fk_Viaje multimedia_Viaje1_idx` (`Viaje_Viaje_ID` ASC, `Viaje_Proyecto_Proy_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Viaje multimedia_Viaje1`
    FOREIGN KEY (`Viaje_Viaje_ID` , `Viaje_Proyecto_Proy_ID`)
    REFERENCES `Proyecto_de_investigacion`.`Viaje` (`Viaje_ID` , `Proyecto_Proy_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Proyecto_de_investigacion`.`Formulario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Proyecto_de_investigacion`.`Formulario` (
  `Formulario_ID` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `Descripcion` TEXT NOT NULL,
  PRIMARY KEY (`Formulario_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Proyecto_de_investigacion`.`Grupo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Proyecto_de_investigacion`.`Grupo` (
  `Grupo_ID` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(100) NOT NULL,
  `Descripcion` TEXT NULL,
  `URL` VARCHAR(225) NULL,
  PRIMARY KEY (`Grupo_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Proyecto_de_investigacion`.`Inv_grupo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Proyecto_de_investigacion`.`Inv_grupo` (
  `Grupo_Grupo_ID` INT NOT NULL,
  `users_User_ID` INT NOT NULL,
  `INV_ID` INT NOT NULL AUTO_INCREMENT,
  `Fecha` DATETIME NOT NULL,
  `Estado` VARCHAR(45) NOT NULL DEFAULT 'En espera',
  PRIMARY KEY (`INV_ID`, `Grupo_Grupo_ID`, `users_User_ID`),
  INDEX `fk_Grupo_has_users_users1_idx` (`users_User_ID` ASC) VISIBLE,
  INDEX `fk_Grupo_has_users_Grupo1_idx` (`Grupo_Grupo_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Grupo_has_users_Grupo1`
    FOREIGN KEY (`Grupo_Grupo_ID`)
    REFERENCES `Proyecto_de_investigacion`.`Grupo` (`Grupo_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Grupo_has_users_users1`
    FOREIGN KEY (`users_User_ID`)
    REFERENCES `Proyecto_de_investigacion`.`users` (`User_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Proyecto_de_investigacion`.`Grupo_has_users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Proyecto_de_investigacion`.`Grupo_has_users` (
  `Grupo_Grupo_ID` INT NOT NULL,
  `users_User_ID` INT NOT NULL,
  `Admin` BINARY(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`Grupo_Grupo_ID`, `users_User_ID`),
  INDEX `fk_Grupo_has_users1_users1_idx` (`users_User_ID` ASC) VISIBLE,
  INDEX `fk_Grupo_has_users1_Grupo1_idx` (`Grupo_Grupo_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Grupo_has_users1_Grupo1`
    FOREIGN KEY (`Grupo_Grupo_ID`)
    REFERENCES `Proyecto_de_investigacion`.`Grupo` (`Grupo_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Grupo_has_users1_users1`
    FOREIGN KEY (`users_User_ID`)
    REFERENCES `Proyecto_de_investigacion`.`users` (`User_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Proyecto_de_investigacion`.`Proyecto_has_Grupo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Proyecto_de_investigacion`.`Proyecto_has_Grupo` (
  `Proyecto_Proy_ID` INT NOT NULL,
  `Grupo_Grupo_ID` INT NOT NULL,
  PRIMARY KEY (`Proyecto_Proy_ID`, `Grupo_Grupo_ID`),
  INDEX `fk_Proyecto_has_Grupo_Grupo1_idx` (`Grupo_Grupo_ID` ASC) VISIBLE,
  INDEX `fk_Proyecto_has_Grupo_Proyecto1_idx` (`Proyecto_Proy_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Proyecto_has_Grupo_Proyecto1`
    FOREIGN KEY (`Proyecto_Proy_ID`)
    REFERENCES `Proyecto_de_investigacion`.`Proyecto` (`Proy_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Proyecto_has_Grupo_Grupo1`
    FOREIGN KEY (`Grupo_Grupo_ID`)
    REFERENCES `Proyecto_de_investigacion`.`Grupo` (`Grupo_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Proyecto_de_investigacion`.`users_has_Formulario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Proyecto_de_investigacion`.`users_has_Formulario` (
  `users_User_ID` INT NOT NULL,
  `Formulario_Formulario_ID` INT NOT NULL,
  PRIMARY KEY (`users_User_ID`, `Formulario_Formulario_ID`),
  INDEX `fk_users_has_Formulario_Formulario1_idx` (`Formulario_Formulario_ID` ASC) VISIBLE,
  INDEX `fk_users_has_Formulario_users1_idx` (`users_User_ID` ASC) VISIBLE,
  CONSTRAINT `fk_users_has_Formulario_users1`
    FOREIGN KEY (`users_User_ID`)
    REFERENCES `Proyecto_de_investigacion`.`users` (`User_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_has_Formulario_Formulario1`
    FOREIGN KEY (`Formulario_Formulario_ID`)
    REFERENCES `Proyecto_de_investigacion`.`Formulario` (`Formulario_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `Proyecto_de_investigacion`.`Fotos_presentacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Proyecto_de_investigacion`.`Fotos_presentacion` (
  `Foto_ID` INT NOT NULL AUTO_INCREMENT,
  `URL` VARCHAR(225) NOT NULL,
  `Presentacion_Presentacion_ID` INT NOT NULL,
  `Presentacion_Proyecto_Proy_ID` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`Foto_ID`, `Presentacion_Presentacion_ID`, `Presentacion_Proyecto_Proy_ID`),
  INDEX `fk_Fotos presentacion_Presentacion1_idx` (`Presentacion_Presentacion_ID` ASC, `Presentacion_Proyecto_Proy_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Fotos presentacion_Presentacion1`
    FOREIGN KEY (`Presentacion_Presentacion_ID` , `Presentacion_Proyecto_Proy_ID`)
    REFERENCES `Proyecto_de_investigacion`.`Presentacion` (`Presentacion_ID` , `Proyecto_Proy_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Proyecto_de_investigacion`.`Fotos_reunion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Proyecto_de_investigacion`.`Fotos_reunion` (
  `Foto_ID` INT NOT NULL AUTO_INCREMENT,
  `URL` VARCHAR(225) NOT NULL,
  `Reunion_Reunion_ID` INT NOT NULL,
  `Reunion_Proyecto_Proy_ID` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`Foto_ID`, `Reunion_Reunion_ID`, `Reunion_Proyecto_Proy_ID`),
  INDEX `fk_Fotos reunion_Reunion1_idx` (`Reunion_Reunion_ID` ASC, `Reunion_Proyecto_Proy_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Fotos reunion_Reunion1`
    FOREIGN KEY (`Reunion_Reunion_ID` , `Reunion_Proyecto_Proy_ID`)
    REFERENCES `Proyecto_de_investigacion`.`Reunion` (`Reunion_ID` , `Proyecto_Proy_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Proyecto_de_investigacion`.`Fotos_users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Proyecto_de_investigacion`.`Fotos_users` (
  `Foto_ID` INT NOT NULL AUTO_INCREMENT,
  `URL` VARCHAR(225) NOT NULL,
  `users_User_ID` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`Foto_ID`, `users_User_ID`),
  INDEX `fk_Fotos users_users1_idx` (`users_User_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Fotos users_users1`
    FOREIGN KEY (`users_User_ID`)
    REFERENCES `Proyecto_de_investigacion`.`users` (`User_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Proyecto_de_investigacion`.`Fotos_grupo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Proyecto_de_investigacion`.`Fotos_grupo` (
  `Foto_ID` INT NOT NULL AUTO_INCREMENT,
  `URL` VARCHAR(225) NOT NULL,
  `Grupo_Grupo_ID` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`Foto_ID`, `Grupo_Grupo_ID`),
  INDEX `fk_Fotos_grupo_Grupo1_idx` (`Grupo_Grupo_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Fotos_grupo_Grupo1`
    FOREIGN KEY (`Grupo_Grupo_ID`)
    REFERENCES `Proyecto_de_investigacion`.`Grupo` (`Grupo_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Proyecto_de_investigacion`.`Fotos_viaje`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Proyecto_de_investigacion`.`Fotos_viaje` (
  `Foto_ID` INT NOT NULL AUTO_INCREMENT,
  `URL` VARCHAR(225) NOT NULL,
  `Viaje_Viaje_ID` INT NOT NULL,
  `Viaje_Proyecto_Proy_ID` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`Foto_ID`, `Viaje_Viaje_ID`, `Viaje_Proyecto_Proy_ID`),
  INDEX `fk_Fotos_viaje_Viaje1_idx` (`Viaje_Viaje_ID` ASC, `Viaje_Proyecto_Proy_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Fotos_viaje_Viaje1`
    FOREIGN KEY (`Viaje_Viaje_ID` , `Viaje_Proyecto_Proy_ID`)
    REFERENCES `Proyecto_de_investigacion`.`Viaje` (`Viaje_ID` , `Proyecto_Proy_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Proyecto_de_investigacion`.`Fotos_proy`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Proyecto_de_investigacion`.`Fotos_proy` (
  `Foto_ID` INT NOT NULL AUTO_INCREMENT,
  `URL` VARCHAR(225) NOT NULL,
  `Proyecto_Proy_ID` INT NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Foto_ID`, `Proyecto_Proy_ID`),
  INDEX `fk_Fotos_proy_Proyecto1_idx` (`Proyecto_Proy_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Fotos_proy_Proyecto1`
    FOREIGN KEY (`Proyecto_Proy_ID`)
    REFERENCES `Proyecto_de_investigacion`.`Proyecto` (`Proy_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Proyecto_de_investigacion`.`Documetos_presentacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Proyecto_de_investigacion`.`Documetos_presentacion` (
  `Documento_ID` INT NOT NULL AUTO_INCREMENT,
  `URL` VARCHAR(225) NOT NULL,
  `Presentacion_Presentacion_ID` INT NOT NULL,
  `Presentacion_Proyecto_Proy_ID` INT NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Documento_ID`, `Presentacion_Presentacion_ID`, `Presentacion_Proyecto_Proy_ID`),
  INDEX `fk_Documetos_pres_Presentacion1_idx` (`Presentacion_Presentacion_ID` ASC, `Presentacion_Proyecto_Proy_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Documetos_pres_Presentacion1`
    FOREIGN KEY (`Presentacion_Presentacion_ID` , `Presentacion_Proyecto_Proy_ID`)
    REFERENCES `Proyecto_de_investigacion`.`Presentacion` (`Presentacion_ID` , `Proyecto_Proy_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Proyecto_de_investigacion`.`Documentos_reunion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Proyecto_de_investigacion`.`Documentos_reunion` (
  `Documento_ID` INT NOT NULL,
  `URL` VARCHAR(225) NOT NULL,
  `Reunion_Reunion_ID` INT NOT NULL,
  `Reunion_Proyecto_Proy_ID` INT NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Documento_ID`, `Reunion_Reunion_ID`, `Reunion_Proyecto_Proy_ID`),
  INDEX `fk_Documentos_reunion_Reunion1_idx` (`Reunion_Reunion_ID` ASC, `Reunion_Proyecto_Proy_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Documentos_reunion_Reunion1`
    FOREIGN KEY (`Reunion_Reunion_ID` , `Reunion_Proyecto_Proy_ID`)
    REFERENCES `Proyecto_de_investigacion`.`Reunion` (`Reunion_ID` , `Proyecto_Proy_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
