-- MySQL Script generated by MySQL Workbench
-- Sat Jun 13 22:34:09 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Proyecto_de_investigacion
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Proyecto_de_investigacion
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Proyecto_de_investigacion` DEFAULT CHARACTER SET utf8 ;
USE `Proyecto_de_investigacion` ;

-- -----------------------------------------------------
-- Table `Proyecto_de_investigacion`.`Grupo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Proyecto_de_investigacion`.`Grupo` (
  `Grup_ID` INT NOT NULL AUTO_INCREMENT,
  `Grup_nombre` VARCHAR(225) NOT NULL,
  `Grup_desc` TEXT NOT NULL,
  `Grup_esp` VARCHAR(225) NOT NULL,
  `Grup_pag` VARCHAR(225) NOT NULL,
  PRIMARY KEY (`Grup_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Proyecto_de_investigacion`.`Proyecto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Proyecto_de_investigacion`.`Proyecto` (
  `Proy_ID` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(255) NOT NULL,
  `Descripcion` TEXT NULL,
  `Estado` VARCHAR(255) NOT NULL,
  `Grupo_Grup_ID` INT NOT NULL,
  PRIMARY KEY (`Proy_ID`),
  INDEX `fk_Proyecto_Grupo1_idx` (`Grupo_Grup_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Proyecto_Grupo1`
    FOREIGN KEY (`Grupo_Grup_ID`)
    REFERENCES `Proyecto_de_investigacion`.`Grupo` (`Grup_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Proyecto_de_investigacion`.`Reunion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Proyecto_de_investigacion`.`Reunion` (
  `Reunion_ID` INT NOT NULL AUTO_INCREMENT,
  `Titulo` VARCHAR(225) NOT NULL,
  `Descripcion` TEXT NULL,
  `Lugar` VARCHAR(225) NOT NULL,
  `Hora` TIME NOT NULL,
  `Minuta` TEXT NOT NULL,
  `Documento` BLOB NULL,
  `Proyecto_Proy_ID` INT NOT NULL,
  `Fecha` DATE NOT NULL,
  PRIMARY KEY (`Reunion_ID`),
  INDEX `fk_Reunion_Proyecto1_idx` (`Proyecto_Proy_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Reunion_Proyecto1`
    FOREIGN KEY (`Proyecto_Proy_ID`)
    REFERENCES `Proyecto_de_investigacion`.`Proyecto` (`Proy_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Proyecto_de_investigacion`.`Entregables`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Proyecto_de_investigacion`.`Entregables` (
  `Ent_ID` INT NOT NULL AUTO_INCREMENT,
  `Ent_titulo` VARCHAR(225) NOT NULL,
  `Ent_desc` VARCHAR(225) NOT NULL,
  `Ent_fecha` DATETIME NOT NULL,
  `Ent_doc` BLOB NOT NULL,
  `Proyecto_Proy_ID` INT NOT NULL,
  PRIMARY KEY (`Ent_ID`),
  INDEX `fk_Entregables_Proyecto1_idx` (`Proyecto_Proy_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Entregables_Proyecto1`
    FOREIGN KEY (`Proyecto_Proy_ID`)
    REFERENCES `Proyecto_de_investigacion`.`Proyecto` (`Proy_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Proyecto_de_investigacion`.`Reporte`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Proyecto_de_investigacion`.`Reporte` (
  `Rep_ID` INT NOT NULL AUTO_INCREMENT,
  `Proy_ID` INT NOT NULL,
  `Nombre` VARCHAR(225) NOT NULL,
  `Fecha_Ini` DATETIME NOT NULL,
  `Fecha_Fin` DATETIME NOT NULL,
  `Proyecto_Proy_ID` INT NOT NULL,
  PRIMARY KEY (`Rep_ID`),
  INDEX `fk_Reporte_Proyecto1_idx` (`Proyecto_Proy_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Reporte_Proyecto1`
    FOREIGN KEY (`Proyecto_Proy_ID`)
    REFERENCES `Proyecto_de_investigacion`.`Proyecto` (`Proy_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Proyecto_de_investigacion`.`Viaje`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Proyecto_de_investigacion`.`Viaje` (
  `Viaje_ID` INT NOT NULL AUTO_INCREMENT,
  `Fecha_Ini` DATETIME NOT NULL,
  `Fecha_Fin` DATETIME NOT NULL,
  `motivo` TEXT NULL,
  `lugar` VARCHAR(225) NULL,
  `Proyecto_Proy_ID` INT NOT NULL,
  PRIMARY KEY (`Viaje_ID`),
  INDEX `fk_Viaje_Proyecto1_idx` (`Proyecto_Proy_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Viaje_Proyecto1`
    FOREIGN KEY (`Proyecto_Proy_ID`)
    REFERENCES `Proyecto_de_investigacion`.`Proyecto` (`Proy_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `Proyecto_de_investigacion`.`viajes_multimedia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Proyecto_de_investigacion`.`viajes_multimedia` (
  `Viaje_Multimedia_ID` INT NOT NULL AUTO_INCREMENT,
  `ID_Viaje` INT NOT NULL,
  `URL` TEXT NULL,
  PRIMARY KEY (`Viaje_Multimedia_ID`),
    FOREIGN KEY (`ID_Viaje`)
    REFERENCES `Proyecto_de_investigacion`.`Viaje` (`Viaje_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `Proyecto_de_investigacion`.`Presentacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Proyecto_de_investigacion`.`Presentacion` (
  `Presentacion_ID` INT NOT NULL AUTO_INCREMENT,
  `Titulo` VARCHAR(225) NOT NULL,
  `Fecha` DATETIME NOT NULL,
  `Lugar` VARCHAR(225) NOT NULL,
  `Presentador` VARCHAR(225) NOT NULL,
  `Descripcion` TEXT NOT NULL,
  `Presen_ID` INT NOT NULL,
  `Proyecto_Proy_ID` INT NOT NULL,
  PRIMARY KEY (`Presentacion_ID`),
  INDEX `fk_Presentacion_Proyecto1_idx` (`Proyecto_Proy_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Presentacion_Proyecto1`
    FOREIGN KEY (`Proyecto_Proy_ID`)
    REFERENCES `Proyecto_de_investigacion`.`Proyecto` (`Proy_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Proyecto_de_investigacion`.`Inv proy`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Proyecto_de_investigacion`.`Inv_proy` (
  `Not_ID` INT NOT NULL AUTO_INCREMENT,
  `Fecha` DATETIME NOT NULL,
  `Estado` VARCHAR(45) NOT NULL,
  `Proyecto_Proy_ID` INT NOT NULL,
  `users_User_Proy_ID` INT NOT NULL,
  PRIMARY KEY (`Not_ID`, `Proyecto_Proy_ID`),
  INDEX `fk_Inv proy_Proyecto1_idx` (`Proyecto_Proy_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Inv proy_Proyecto1`
    FOREIGN KEY (`Proyecto_Proy_ID`)
    REFERENCES `Proyecto_de_investigacion`.`Proyecto` (`Proy_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Notificacion_users_proy1`
    FOREIGN KEY (`users_User_Proy_ID`)
    REFERENCES `Proyecto_de_investigacion`.`users` (`User_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Proyecto_de_investigacion`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Proyecto_de_investigacion`.`users` (
  `User_ID` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(32) NOT NULL,
  `usuario` VARCHAR(32) NOT NULL,
  `descripcion` Text NOT NULL,
  PRIMARY KEY (`User_ID`)
  );


-- -----------------------------------------------------
-- Table `Proyecto_de_investigacion`.`Inv grupo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Proyecto_de_investigacion`.`Inv grupo` (
  `Not_ID` INT NOT NULL AUTO_INCREMENT,
  `Fecha` DATETIME NOT NULL,
  `Estado` VARCHAR(225) NOT NULL,
  `Grupo_Grup_ID` INT NOT NULL,
  `users_User_ID` INT NOT NULL,
  PRIMARY KEY (`Not_ID`, `Grupo_Grup_ID`, `users_User_ID`),
  INDEX `fk_Notificacion_Grupo1_idx` (`Grupo_Grup_ID` ASC) VISIBLE,
  INDEX `fk_Notificacion_users1_idx` (`users_User_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Notificacion_Grupo1`
    FOREIGN KEY (`Grupo_Grup_ID`)
    REFERENCES `Proyecto_de_investigacion`.`Grupo` (`Grup_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Notificacion_users1`
    FOREIGN KEY (`users_User_ID`)
    REFERENCES `Proyecto_de_investigacion`.`users` (`User_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Proyecto_de_investigacion`.`Documento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Proyecto_de_investigacion`.`Documento` (
  `Doc_ID` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(225) NOT NULL,
  `Descripcion` TEXT NOT NULL,
  `Tipo` VARCHAR(225) NOT NULL,
  `Proyecto_Proy_ID` INT NOT NULL,
  `Entregables_Ent_ID` INT NOT NULL,
  PRIMARY KEY (`Doc_ID`, `Entregables_Ent_ID`),
  INDEX `fk_Documento_Proyecto1_idx` (`Proyecto_Proy_ID` ASC) VISIBLE,
  INDEX `fk_Documento_Entregables1_idx` (`Entregables_Ent_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Documento_Proyecto1`
    FOREIGN KEY (`Proyecto_Proy_ID`)
    REFERENCES `Proyecto_de_investigacion`.`Proyecto` (`Proy_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Documento_Entregables1`
    FOREIGN KEY (`Entregables_Ent_ID`)
    REFERENCES `Proyecto_de_investigacion`.`Entregables` (`Ent_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Proyecto_de_investigacion`.`Categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Proyecto_de_investigacion`.`Categoria` (
  `Cat_ID` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(225) NOT NULL,
  `Area` VARCHAR(225) NOT NULL,
  `Descripcion` TEXT NULL,
  PRIMARY KEY (`Cat_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Proyecto_de_investigacion`.`users_has_Grupo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Proyecto_de_investigacion`.`users_has_Grupo` (
  `users_User_ID` INT NOT NULL,
  `Grupo_Grup_ID` INT NOT NULL,
  `Admin` BINARY(1) NULL DEFAULT 0,
  PRIMARY KEY (`users_User_ID`, `Grupo_Grup_ID`),
  INDEX `fk_users_has_Grupo_Grupo1_idx` (`Grupo_Grup_ID` ASC) VISIBLE,
  INDEX `fk_users_has_Grupo_users_idx` (`users_User_ID` ASC) VISIBLE,
  CONSTRAINT `fk_users_has_Grupo_users`
    FOREIGN KEY (`users_User_ID`)
    REFERENCES `Proyecto_de_investigacion`.`users` (`User_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_has_Grupo_Grupo1`
    FOREIGN KEY (`Grupo_Grup_ID`)
    REFERENCES `Proyecto_de_investigacion`.`Grupo` (`Grup_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `Proyecto_de_investigacion`.`users_has_Proyecto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Proyecto_de_investigacion`.`users_has_Proyecto` (
  `users_User_ID` INT NOT NULL,
  `Proyecto_Proy_ID` INT NOT NULL,
  `JP` BINARY(1) NULL DEFAULT 0,
  `Permisos de editado` BINARY(1) NULL DEFAULT 1,
  PRIMARY KEY (`users_User_ID`, `Proyecto_Proy_ID`),
  INDEX `fk_users_has_Proyecto_Proyecto1_idx` (`Proyecto_Proy_ID` ASC) VISIBLE,
  INDEX `fk_users_has_Proyecto_users1_idx` (`users_User_ID` ASC) VISIBLE,
  CONSTRAINT `fk_users_has_Proyecto_users1`
    FOREIGN KEY (`users_User_ID`)
    REFERENCES `Proyecto_de_investigacion`.`users` (`User_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_has_Proyecto_Proyecto1`
    FOREIGN KEY (`Proyecto_Proy_ID`)
    REFERENCES `Proyecto_de_investigacion`.`Proyecto` (`Proy_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `Proyecto_de_investigacion`.`Presentacion_has_users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Proyecto_de_investigacion`.`Presentacion_has_users` (
  `Presentacion_Presentacion_ID` INT NOT NULL,
  `Presentacion_Proyecto_Proy_ID` INT NOT NULL,
  `users_User_ID` INT NOT NULL,
  PRIMARY KEY (`Presentacion_Presentacion_ID`, `Presentacion_Proyecto_Proy_ID`, `users_User_ID`),
  INDEX `fk_Presentacion_has_users_users1_idx` (`users_User_ID` ASC) VISIBLE,
  INDEX `fk_Presentacion_has_users_Presentacion1_idx` (`Presentacion_Presentacion_ID` ASC, `Presentacion_Proyecto_Proy_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Presentacion_has_users_Presentacion1`
    FOREIGN KEY (`Presentacion_Presentacion_ID` , `Presentacion_Proyecto_Proy_ID`)
    REFERENCES `Proyecto_de_investigacion`.`Presentacion` (`Presentacion_ID` , `Proyecto_Proy_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Presentacion_has_users_users1`
    FOREIGN KEY (`users_User_ID`)
    REFERENCES `Proyecto_de_investigacion`.`users` (`User_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Proyecto_de_investigacion`.`Proyecto_has_Categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Proyecto_de_investigacion`.`Proyecto_has_Categoria` (
  `Proyecto_Proy_ID` INT NOT NULL,
  `Categoria_Cat_ID` INT NOT NULL,
  PRIMARY KEY (`Proyecto_Proy_ID`, `Categoria_Cat_ID`),
  INDEX `fk_Proyecto_has_Categoria_Categoria1_idx` (`Categoria_Cat_ID` ASC) VISIBLE,
  INDEX `fk_Proyecto_has_Categoria_Proyecto1_idx` (`Proyecto_Proy_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Proyecto_has_Categoria_Proyecto1`
    FOREIGN KEY (`Proyecto_Proy_ID`)
    REFERENCES `Proyecto_de_investigacion`.`Proyecto` (`Proy_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Proyecto_has_Categoria_Categoria1`
    FOREIGN KEY (`Categoria_Cat_ID`)
    REFERENCES `Proyecto_de_investigacion`.`Categoria` (`Cat_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Proyecto_de_investigacion`.`Viaje_has_users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Proyecto_de_investigacion`.`Viaje_has_users` (
  `Viaje_Viaje_ID` INT NOT NULL,
  `users_User_ID` INT NOT NULL,
  PRIMARY KEY (`Viaje_Viaje_ID`, `users_User_ID`),
  INDEX `fk_Viaje_has_users_users1_idx` (`users_User_ID` ASC) VISIBLE,
  INDEX `fk_Viaje_has_users_Viaje1_idx` (`Viaje_Viaje_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Viaje_has_users_Viaje1`
    FOREIGN KEY (`Viaje_Viaje_ID`)
    REFERENCES `Proyecto_de_investigacion`.`Viaje` (`Viaje_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Viaje_has_users_users1`
    FOREIGN KEY (`users_User_ID`)
    REFERENCES `Proyecto_de_investigacion`.`users` (`User_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
